/*
 *  Copyright 2010-2019 Neotropic SAS <contact@neotropic.co>.
 *
 *  Licensed under the EPL License, Version 1.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.eclipse.org/legal/epl-v10.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.neotropic.kuwaiba.integration.proxies;

import javax.security.auth.RefreshFailedException;
import javax.security.auth.Refreshable;
import org.neotropic.kuwaiba.integration.proxies.nodes.ProxyRootNode;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.neotropic.kuwaiba.integration.proxies//Proxy//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ProxyTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "explorer", openAtStartup = false)
@ActionID(category = "Window", id = "org.neotropic.kuwaiba.integration.proxies.ProxyTopComponent")
@ActionReference(path = "Menu/Tools/Integration" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ProxyAction",
        preferredID = "ProxyTopComponent"
)
@Messages({
    "CTL_ProxyAction=Inventory Proxy Manager",
    "CTL_ProxyTopComponent=Inventory Proxy Manager",
    "HINT_ProxyTopComponent=Manage proxy elements that can group inventory objects when integrating Kuwaiba with third party applications"
})
public final class ProxyTopComponent extends TopComponent 
                implements ExplorerManager.Provider, Refreshable {
    
    private ExplorerManager em = new ExplorerManager();

    public ProxyTopComponent() {
        initComponents();
        initCustomComponents();
        setName(Bundle.CTL_ProxyTopComponent());
        setToolTipText(Bundle.HINT_ProxyTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void componentOpened() {
        em.setRootContext(new ProxyRootNode());
    }

    @Override
    public void componentClosed() {
        em.getRootContext().getChildren().remove(em.getRootContext().getChildren().getNodes());
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    @Override
    public boolean isCurrent() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void refresh() throws RefreshFailedException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void initCustomComponents() {
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        add(new BeanTreeView());
    }
}
