/*
 *  Copyright 2010, 2011, 2012 Neotropic SAS <contact@neotropic.co>.
 *
 *  Licensed under the EPL License, Version 1.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.eclipse.org/legal/epl-v10.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.inventory.communications.core;

import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.util.HashMap;
import org.inventory.core.services.api.metadata.LocalClassMetadataLight;
import org.inventory.core.services.utils.Utils;
import org.kuwaiba.wsclient.ClassInfo;
import org.kuwaiba.wsclient.ClassInfoLight;
import org.kuwaiba.wsclient.Validator;
import org.openide.util.lookup.ServiceProvider;

/**
 * Implementation of the common interface to represent the classmetadata in a simple
 * way so it can be shown in trees and lists. This is done because to bring the whole
 * metadata is not necessary (ie. Container Hierarchy Manager)
 * @author Charles Edward Bedon Cortazar <charles.bedon@kuwaiba.org>
 */
@ServiceProvider(service=LocalClassMetadataLight.class)
public class LocalClassMetadataLightImpl
        implements LocalClassMetadataLight,Transferable{

    /**
     * Class id
     */
    protected Long id;
    /**
     * Is this class abstract?
     */
    protected boolean abstractClass;
    /**
     * Is this class subclass of viewable? (this is, can have views attached)
     */
    protected boolean viewable;
    /**
     * Is this class subclass of GenericObject list? (this is, a list type)
     */
    protected boolean listType;
    /**
     * Class name
     */
    protected String className;
    /**
     * Class display name
     */
    protected String displayName;
    /**
     * Class icon for trees. This is the icon the instances of this class will show in trees
     */
    protected Image smallIcon;
    /**
     * Misc validators. Validators tell you states of this class related to business rules
     */
    protected HashMap<String, Integer> validators;

    public LocalClassMetadataLightImpl() {    }

    public LocalClassMetadataLightImpl(ClassInfo ci){
        this.id = ci.getId();
        this.abstractClass = ci.isAbstractClass();
        this.viewable = ci.isViewable();
        this.listType = ci.isListType();
        this.className = ci.getClassName();
        this.displayName = ci.getDisplayName();
        this.smallIcon = ci.getSmallIcon()==null ? null : Utils.getImageFromByteArray(ci.getSmallIcon());
        this.validators = new HashMap<String, Integer>();

        for (Validator validator : ci.getValidators())
            validators.put(validator.getLabel(), validator.getValue());
    }

    /**
     * Note: ClassInfoLight is not super class of ClassInfo. They're stubs generated by the ws client
     * @param cil
     */
    public LocalClassMetadataLightImpl(ClassInfoLight cil){
        this.id = cil.getId();
        this.abstractClass = cil.isAbstractClass();
        this.viewable = cil.isViewable();
        this.listType = cil.isListType();
        this.className = cil.getClassName();
        this.displayName = cil.getDisplayName();
        this.smallIcon = cil.getSmallIcon()==null ? null : Utils.getImageFromByteArray(cil.getSmallIcon());
        this.validators = new HashMap<String, Integer>();

        for (Validator validator : cil.getValidators())
            validators.put(validator.getLabel(), validator.getValue());

    }

    public LocalClassMetadataLightImpl(Long id, String className, String displayName,
            byte[] smallIcon, boolean isAbstract, boolean isViewable, boolean isListType, HashMap<String, Integer> validators){
        this.id = id;
        this.abstractClass = isAbstract;
        this.viewable = isViewable;
        this.listType = isListType;
        this.className = className;
        this.displayName = displayName;
        this.smallIcon = smallIcon==null ? null : Utils.getImageFromByteArray(smallIcon);
        this.validators = validators;
    }

    public LocalClassMetadataLightImpl(Long id, String className, String displayName,
            Image smallIcon, boolean isAbstract, boolean isViewable, boolean isListType, HashMap<String, Integer> validators){
        this.id = id;
        this.abstractClass = isAbstract;
        this.viewable = isViewable;
        this.listType = isListType;
        this.className = className;
        this.displayName = displayName;
        this.smallIcon = smallIcon;
        this.validators = validators;
    }

    public String getClassName() {
        return className;
    }

    public Long getOid() {
        return id;
    }

    @Override
    public String toString(){
        return className;
    }

    public boolean isAbstract() {
        return abstractClass;
    }

    public boolean isViewable(){
        return this.viewable;
    }

    public boolean isListType(){
        return this.listType;
    }

   /**
    * The equals method is overwritten in order to make the comparison based on the id, which is
    * the actual unique identifier (this is used when filtering the list of possible children in the Hierarchy Manager)
    */
   @Override
   public boolean equals(Object obj){
       if(obj == null)
           return false;
       if (!(obj instanceof LocalClassMetadataLight))
           return false;
       if (this.getOid() == null || ((LocalClassMetadataLight)obj).getOid() == null)
           return false;
       return (this.getOid().longValue() == ((LocalClassMetadataLight)obj).getOid().longValue());
   }

    @Override
    public int hashCode() {
        int hash = 9;
        hash = 81 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }
    
    public String getDisplayName(){
        if (displayName == null)
            return className;
        if (displayName.trim().equals(""))
            return className;
        return displayName;
    }
    
    public Image getSmallIcon() {
        return smallIcon;
    }

    public void setSmallIcon(Image newIcon){
        this.smallIcon = newIcon;
    }

    public DataFlavor[] getTransferDataFlavors() {
        return new DataFlavor[]{LocalClassMetadataLight.DATA_FLAVOR};
    }

    /**
     * Retrieves the value of a given validator
     * @param validatorName validator's name
     * @return value for the given validator. false if the validator is not present
     */
    public int getValidator(String validatorName){
        return validators.get(validatorName) == null ? 0 : validators.get(validatorName);
    }

    public boolean isDataFlavorSupported(DataFlavor flavor) {
        return flavor.equals(LocalClassMetadataLight.DATA_FLAVOR);
    }

    public Object getTransferData(DataFlavor flavor) throws UnsupportedFlavorException, IOException {
        if (isDataFlavorSupported(flavor))
            return this;
        else
            throw new UnsupportedFlavorException(flavor);
    }
}