/*
 *  Copyright 2010, 2011, 2012 Neotropic SAS <contact@neotropic.co>.
 *
 *  Licensed under the EPL License, Version 1.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.eclipse.org/legal/epl-v10.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.inventory.communications.core;

import java.awt.Image;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.inventory.core.services.api.metadata.LocalClassMetadataLight;
import org.inventory.core.services.utils.Utils;
import org.kuwaiba.wsclient.ClassInfo;
import org.kuwaiba.wsclient.ClassInfoLight;
import org.kuwaiba.wsclient.Validator;
import org.openide.util.lookup.ServiceProvider;

/**
 * Implementation of the common interface to represent the classmetadata in a simple
 * way so it can be shown in trees and lists. This is done because to bring the whole
 * metadata is not necessary (ie. Container Hierarchy Manager)
 * @author Charles Edward Bedon Cortazar <charles.bedon@kuwaiba.org>
 */
@ServiceProvider(service=LocalClassMetadataLight.class)
public class LocalClassMetadataLightImpl implements LocalClassMetadataLight{
    /**
     * Class id
     */
    protected long id;
    /**
     * Class name
     */
    protected String className;
    /**
     * Class display name
     */
    protected String displayName;
    /**
     * Parent ClassMetada name
     */
    protected String parentName;
    /**
     * Is this class abstract?
     */
    protected boolean _abstract;
    /**
     * Is this class subclass of viewable? (this is, can have views attached)
     */
    protected boolean viewable;
    /**
     * Is this class subclass of GenericObject list? (this is, a list type)
     */
    protected boolean listType;
    /**
     * Shows if this is a core class (the ones provided in the official release) or a custom one
     */
    protected boolean custom;
    /**
     * Is the class "operational" or is it in design process?
     */
    protected boolean inDesign;

    /**
     * Class icon for trees. This is the icon the instances of this class will show in trees
     */
    protected Image smallIcon;
    /**
     * Misc validators. Validators tell you states of this class related to business rules
     */
    protected HashMap<String, Integer> validators;
    /**
     * The list of property change listeners
     */
    protected List<PropertyChangeListener> propertyChangeListeners;
    /**
     * This constructor is called to create dummy class metadata objects, such as that used to represent the Navigation Tree root
     */
    public LocalClassMetadataLightImpl() {  this.id = -1;  }
    
    public LocalClassMetadataLightImpl(ClassInfo ci){
        this.id = ci.getId();
        this._abstract = ci.isAbstract();
        this.viewable = ci.isViewable();
        this.listType = ci.isListType();
        this.custom = ci.isCustom();
        this.inDesign = ci.isInDesign();
        this.className = ci.getClassName();
        this.displayName = ci.getDisplayName();
        this.parentName = ci.getParentClassName();
        this.smallIcon = ci.getSmallIcon()==null ? null : Utils.getImageFromByteArray(ci.getSmallIcon());
        this.validators = new HashMap<String, Integer>();

        for (Validator validator : ci.getValidators()){
            validators.put(validator.getLabel(), validator.getValue());
        }
    }

    /**
     * Note: ClassInfoLight is not super class of ClassInfo. They're stubs generated by the ws client
     * @param cil
     */
    public LocalClassMetadataLightImpl(ClassInfoLight cil){
        this.id = cil.getId();
        this._abstract = cil.isAbstract();
        this.viewable = cil.isViewable();
        this.listType = cil.isListType();
        this.custom = cil.isCustom();
        this.inDesign = cil.isInDesign();
        this.className = cil.getClassName();
        this.displayName = cil.getDisplayName();
        this.parentName = cil.getParentClassName();
        this.smallIcon = cil.getSmallIcon()==null ? null : Utils.getImageFromByteArray(cil.getSmallIcon());
        this.validators = new HashMap<String, Integer>();

        for (Validator validator : cil.getValidators())
            validators.put(validator.getLabel(), validator.getValue());
    }

    public LocalClassMetadataLightImpl(long id, String className, String displayName, String parentName,
            byte[] smallIcon, boolean _abstract, boolean isViewable, boolean isListType, boolean isCustom, boolean isInDesign, HashMap<String, Integer> validators){
        this.id = id;
        this._abstract = _abstract;
        this.viewable = isViewable;
        this.listType = isListType;
        this.custom = isCustom;
        this.inDesign = isInDesign;
        this.className = className;
        this.displayName = displayName;
        this.parentName = parentName;
        this.smallIcon = smallIcon==null ? null : Utils.getImageFromByteArray(smallIcon);
        this.validators = validators;
    }

    public LocalClassMetadataLightImpl(long id, String className, String displayName, String parentName,
            Image smallIcon, boolean _abstract, boolean isViewable, boolean isListType, HashMap<String, Integer> validators){
        this.id = id;
        this._abstract = _abstract;
        this.viewable = isViewable;
        this.listType = isListType;
        this.className = className;
        this.displayName = displayName;
        this.parentName = parentName;
        this.smallIcon = smallIcon;
        this.validators = validators;
    }

    @Override
    public String getClassName() {
        return className;
    }
    
    @Override
    public void setClassName(String className) {
        this.className = className;
    }

    @Override
    public long getOid() {
        return id;
    }

    @Override
    public void setOid(long id) {
        this.id = id;
    }
    
    @Override
    public String toString(){
        return className;
    }

    @Override
    public boolean isAbstract() {
        return _abstract;
    }
    
    @Override
    public void setAbstract(boolean _abstract){
        this._abstract = _abstract;
    }

    @Override
    public boolean isViewable(){
        return this.viewable;
    }
    
    @Override 
    public void setViewable(boolean viewable){
        this.viewable = viewable;
    }

    @Override
    public boolean isListType(){
        return this.listType;
    }
    
    @Override
    public void setListType(boolean listType){
        this.listType = listType;
    }

   /**
    * The equals method is overwritten in order to make the comparison based on the id, which is
    * the actual unique identifier (this is used when filtering the list of possible children in the Hierarchy Manager)
    */
   @Override
   public boolean equals(Object obj){
       if(obj == null) {
           return false;
       }
       if (!(obj instanceof LocalClassMetadataLight)) {
           return false;
       }
       return (this.getOid() == ((LocalClassMetadataLight)obj).getOid());
   }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (int) (this.id ^ (this.id >>> 32));
        hash = 97 * hash + (this.className != null ? this.className.hashCode() : 0);
        return hash;
    }
   
    @Override
    public String getDisplayName(){
        if (displayName == null) {
            return className;
        }
        if (displayName.trim().equals("")) {
            return className;
        }
        return displayName;
    }
    
    @Override 
    public void setDisplayName(String displayName){
        if(displayName != null){
            this.displayName = displayName;
        }
    }
    
    @Override
    public Image getSmallIcon() {
        return smallIcon;
    }

    @Override
    public void setSmallIcon(Image newIcon){
        this.smallIcon = newIcon;
    }

    @Override
    public DataFlavor[] getTransferDataFlavors() {
        return new DataFlavor[]{LocalClassMetadataLight.DATA_FLAVOR};
    }

    /**
     * Retrieves the value of a given validator
     * @param validatorName validator's name
     * @return value for the given validator. false if the validator is not present
     */
    @Override
    public int getValidator(String validatorName){
        return validators.get(validatorName) == null ? 0 : validators.get(validatorName);
    }

    @Override
    public boolean isDataFlavorSupported(DataFlavor flavor) {
        return flavor.equals(LocalClassMetadataLight.DATA_FLAVOR);
    }

    @Override
    public Object getTransferData(DataFlavor flavor) throws UnsupportedFlavorException, IOException {
        if (isDataFlavorSupported(flavor)) {
            return this;
        }
        else {
            throw new UnsupportedFlavorException(flavor);
        }
    }

    @Override
    public String getParentName() {
        return parentName;
    }

    @Override
    public boolean isCustom() {
        return custom;
    }

    @Override
    public void setCustom(boolean custom){
        this.custom = custom;
    }
    
    @Override
    public boolean isInDesign() {
        return inDesign;
    }
    
    @Override
    public void setInDesign(boolean inDesign){
        this.inDesign = inDesign;
    }
    
    @Override
    public void addPropertyChangeListener(PropertyChangeListener newListener){
        if (propertyChangeListeners == null){
            propertyChangeListeners = new ArrayList<PropertyChangeListener>();
        }
        if (propertyChangeListeners.contains(newListener)){
            return;
        }
        propertyChangeListeners.add(newListener);
    }

    @Override
    public void removePropertyChangeListener(PropertyChangeListener listener){
        if (propertyChangeListeners == null){
            return;
        }
        propertyChangeListeners.remove(listener);
    }
    @Override
    public void firePropertyChangeEvent(String property, Object oldValue, Object newValue){
        for (PropertyChangeListener listener : propertyChangeListeners){
            listener.propertyChange(new PropertyChangeEvent(this, property, oldValue, newValue));
        }
    }
 }