/*
 *  Copyright 2010-2017 Neotropic SAS <contact@neotropic.co>.
 * 
 *   Licensed under the EPL License, Version 1.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *        http://www.eclipse.org/legal/epl-v10.html
 * 
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 * 
 */
package com.neotropic.inventory.modules.sync;

import com.neotropic.inventory.modules.sync.actions.KillJobAction;
import com.neotropic.inventory.modules.sync.nodes.SyncGroupRootNode;
import com.neotropic.inventory.modules.sync.nodes.actions.DeleteSyncAction;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;
import org.inventory.core.services.api.behaviors.Refreshable;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.BeanTreeView;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.nodes.Node;

/**
 * Main GUI component to manage the inventory synchronization tasks.
 * @author Adrian Martinez Molina <adrian.martinez@kuwaiba.org>
 */
@ConvertAsProperties(
        dtd = "-//com.neotropic.inventory.modules.sync//SyncManagerTopComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "SyncManagerTopComponent",
        iconBase = "com/neotropic/inventory/modules/sync/res/icon.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = false)
@ActionID(category = "Window", id = "com.neotropic.inventory.modules.sync.SyncTopComponent")
@ActionReference(path = "Menu/Tools/Advanced")
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_SyncAction",
        preferredID = "SyncTopComponent"
)
@Messages({
    "CTL_SyncAction=Inventory Synchronization",
    "CTL_SyncTopComponent=Inventory Sync Manager",
    "HINT_SyncTopComponent=Manage the inventory synchronization tasks"
})
public final class SyncManagerTopComponent extends TopComponent implements 
    ExplorerManager.Provider, Refreshable {

    private BeanTreeView treeMain;
    private final ExplorerManager em;
    
    public SyncManagerTopComponent() {
        em = new ExplorerManager();
        initComponents();
        initCustomComponents();
        setName(Bundle.CTL_SyncTopComponent());
        setToolTipText(Bundle.HINT_SyncTopComponent());
    }
    
    public void initCustomComponents() {
        getActionMap().put(DefaultEditorKit.copyAction, ExplorerUtils.actionCopy(em));
        getActionMap().put(DefaultEditorKit.cutAction, ExplorerUtils.actionCut(em));
        getActionMap().put(DefaultEditorKit.pasteAction, ExplorerUtils.actionPaste(em));
        getActionMap().put(DeleteSyncAction.ACTION_MAP_KEY, DeleteSyncAction.getInstance());
        
        InputMap keys = getInputMap(WHEN_IN_FOCUSED_WINDOW);
        keys.put(KeyStroke.getKeyStroke(KeyEvent.VK_C, KeyEvent.CTRL_DOWN_MASK), DefaultEditorKit.copyAction);
        keys.put(KeyStroke.getKeyStroke(KeyEvent.VK_X, KeyEvent.CTRL_DOWN_MASK), DefaultEditorKit.cutAction);
        keys.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.CTRL_DOWN_MASK), DefaultEditorKit.pasteAction);
        keys.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), DeleteSyncAction.ACTION_MAP_KEY);
        
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        treeMain = new BeanTreeView();
        add(treeMain);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolMain = new javax.swing.JToolBar();
        btnGetJobs = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        toolMain.setRollover(true);

        org.openide.awt.Mnemonics.setLocalizedText(btnGetJobs, org.openide.util.NbBundle.getMessage(SyncManagerTopComponent.class, "SyncManagerTopComponent.btnGetJobs.text")); // NOI18N
        btnGetJobs.setToolTipText(org.openide.util.NbBundle.getMessage(SyncManagerTopComponent.class, "SyncManagerTopComponent.btnGetJobs.toolTipText")); // NOI18N
        btnGetJobs.setFocusable(false);
        btnGetJobs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGetJobs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGetJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetJobsActionPerformed(evt);
            }
        });
        toolMain.add(btnGetJobs);
        btnGetJobs.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(SyncManagerTopComponent.class, "SyncManagerTopComponent.btnGetJobs.AccessibleContext.accessibleName")); // NOI18N

        add(toolMain, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetJobsActionPerformed
        new KillJobAction().actionPerformed(evt);
    }//GEN-LAST:event_btnGetJobsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetJobs;
    private javax.swing.JToolBar toolMain;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        ExplorerUtils.activateActions(em, true);
        em.setRootContext(new SyncGroupRootNode());
    }

    @Override
    public void componentClosed() {
        ExplorerUtils.activateActions(em, false);
        em.setRootContext(Node.EMPTY);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }

    @Override
    public void refresh() {
        componentClosed();
        componentOpened();
    }
}
