/*
 *  Copyright 2010 - 2014 Neotropic SAS <contact@neotropic.co>.
 *
 *  Licensed under the EPL License, Version 1.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *       http://www.eclipse.org/legal/epl-v10.html
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.inventory.view.rackview;

import org.inventory.core.services.api.notifications.NotificationUtil;
import org.inventory.core.visual.actions.ExportSceneAction;
import org.inventory.view.rackview.scene.RackViewScene;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Rack view module main TopComponent
 * @author Charles Edward Bedon Cortazar <charles.bedon@kuwaiba.org>
 */
@ConvertAsProperties(
    dtd = "-//org.inventory.view.rackview//RackView//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "RackViewTopComponent",
iconBase = "org/inventory/view/rackview/res/icon.png",
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.inventory.view.rackview.RackViewTopComponent")
@ActionReferences(value = {@ActionReference(path = "Menu/Tools"),
    @ActionReference(path = "Toolbars/Tools")})
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_RackViewAction",
preferredID = "RackViewTopComponent")
@Messages({
    "CTL_RackViewAction=RackView",
    "CTL_RackViewTopComponent=Rack View",
    "HINT_RackViewTopComponent=Shows the elements inside a rack"
})
public final class RackViewTopComponent extends TopComponent implements ExplorerManager.Provider {
    private ExplorerManager em = new ExplorerManager();
    private RackViewService rvs;
    private NotificationUtil nu;
    private RackViewScene scene;
    
    public RackViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_RackViewTopComponent());
        setToolTipText(Bundle.HINT_RackViewTopComponent());
        associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
        this.nu = Lookup.getDefault().lookup(NotificationUtil.class);
        this.rvs = new RackViewService(this);
        scene = rvs.getScene();
        pnlScrollMain.setViewportView(scene.createView());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlScrollMain = new javax.swing.JScrollPane();
        barMain = new javax.swing.JToolBar();
        btnExport = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        pnlMain.setPreferredSize(new java.awt.Dimension(426, 334));
        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlScrollMain.setMinimumSize(new java.awt.Dimension(100, 100));
        pnlScrollMain.setPreferredSize(new java.awt.Dimension(200, 300));
        pnlMain.add(pnlScrollMain, java.awt.BorderLayout.CENTER);

        barMain.setRollover(true);
        barMain.setPreferredSize(new java.awt.Dimension(100, 34));

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/inventory/view/rackview/res/export.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnExport, org.openide.util.NbBundle.getMessage(RackViewTopComponent.class, "RackViewTopComponent.btnExport.text")); // NOI18N
        btnExport.setFocusable(false);
        btnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        barMain.add(btnExport);

        pnlMain.add(barMain, java.awt.BorderLayout.PAGE_START);

        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        new ExportSceneAction(scene).actionPerformed(evt);
    }//GEN-LAST:event_btnExportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barMain;
    private javax.swing.JButton btnExport;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JScrollPane pnlScrollMain;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        rvs.initializeLookupListener();
    }

    @Override
    public void componentClosed() {
        rvs.terminateLookListener();
        rvs.getScene().clear();
    }

    void writeProperties(java.util.Properties p) {
    }

    void readProperties(java.util.Properties p) {
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return em;
    }
    
    public NotificationUtil getNotifier(){
        return nu;
    }
}