
package org.inventory.communications.wsclient;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServerSideException", targetNamespace = "http://ws.kuwaiba.org/")
public class ServerSideException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerSideException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServerSideException_Exception(String message, ServerSideException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServerSideException_Exception(String message, ServerSideException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.inventory.communications.wsclient.ServerSideException
     */
    public ServerSideException getFaultInfo() {
        return faultInfo;
    }

}
